import DashboardHeader from "@/components/dashboard/dashboard.header";
import DashboardSidebar from "@/components/dashboard/dashboard.sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({ children }) {
  return (
    <div>
      <DashboardHeader />
      <div style={{ display: "flex" }}>
        <DashboardSidebar />
        <main>
          {children}
        </main>
      </div>
    </div>
  );
}
